#!/bin/sh

# Retrieve author information as Git sees it while commiting
AUTHORINFO=$(git var GIT_AUTHOR_IDENT) || exit 1
NAME=$(printf '%s\n\n' "${AUTHORINFO}" | sed -n 's/^\(.*\) <.*$/\1/p')
#EMAIL=$(printf '%s\n\n' "${AUTHORINFO}" | sed -n 's/^.* <\(.*\)> .*$/\1/p')

# If we're trying to commit to repo with not allowed email
if [ "$NAME" != "Cristi Macoviciuc" ] && [ "$NAME" != "Lucian Moisa" ]; then
  echo "You are NOT ALLOWED to commit in 'curs' repo!"
  echo "(your commit name: ${NAME})"
  #echo "EMAIL: {EMAIL}"
  exit 1
fi
